name: Build Docker Image

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t dahao666/sharelatex:${{ github.sha }} .
          docker tag dahao666/sharelatex:${{ github.sha }} dahao666/sharelatex:latest


      - name: Login to Docker Hub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push dahao666/sharelatex:latest
          docker push dahao666/sharelatex:${{ github.sha }}